Union South; 1308 W Dayton St, Madison, WI 53715
Washburn Observatory;1401 Observatory Dr, Madison, WI 53706
Health Sciences Learning Center;750 Highland Ave, Madison, WI 53705
Kohl Center;The Kohl Center, 601 W Dayton St, Madison, WI 53703
Computer Sciences;1210 West Dayton Street, Madison, WI
Memorial Union;800 Langdon St, Madison, WI 53706
Wisconsin State Capital;2 E Main St, Madison, WI 53703
Waisman Center;1500 Highland Ave, Madison, WI 53705
